apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-python-app
  template:
    metadata:
      labels:
        app: ui-python-app
    spec:
      containers:
        - name: python-container
          image: haithammahajna/netflix-ui:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ui-python-service
spec:
  selector:
    app: ui-python-app
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 3000
  type: ClusterIP

